### ISSUE TITLE
Please add these plugins too

### ISSUE THREAD

**Issue by mohammedzamakhan** [johnpapa/vscode-angular-essentials#1]
- [Output Colorizer](https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer)

**Comment by johnpapa** [comment]
neat idea. but i don't think it's needed in this pack

**Comment by andregs** [comment]
May I suggest this one?

https://marketplace.visualstudio.com/items?itemName=pmneo.tsimporter

Thanks for the pack! (and your videos on PluralSight too)
