### ISSUE TITLE
Useless ".ngForm" intellisense in .html files

### ISSUE THREAD

**Issue by vibrunazo** [johnpapa/vscode-angular-essentials#11]
When I have angular essentials installed. Typing a dot anywhere in an .html file will suggest an auto-complete for ".ngForm", allegedly a "component", and will auto complete that if I press enter. This means that any time I type "period, enter" it will write a completely useless ".ngForm" there.

When I disable angular essentials that completely goes away. But I didn't want to have to disable the entire thing. Which one of the add ons is doing this? Is there any setting to disable this?

Example: https://puu.sh/B70Nc/dbe39b3552.png

**Comment by johnpapa** [comment]
you can try disabling one by one to reproduce, then file a report against that extension
