### ISSUE TITLE
Include tslint-language-service instead than vscode-tslint

### ISSUE THREAD

**Issue by mdarefull** [johnpapa/vscode-angular-essentials#17]
For the reasons provided here:
https://github.com/angelozerr/tslint-language-service

This is actually an npm package, not a vscode extension but that is required to be installed to remove some warnings from tsLint and also improves its performance and enable checking that aren't available by using them separated.

It would be nice to add the npm package someway, if not possible, then at least remove vscode-tslint and provide a document the reasons/steps to fix.

**Comment by johnpapa** [comment]
i cant add the npm package in this pack

but i did update the tslint ext
