### ISSUE TITLE
Remove angular language service from the list

### ISSUE THREAD

**Issue by cmeyertons** [johnpapa/vscode-angular-essentials#20]
The Angular language service extension currently seems to be unmaintained by the Angular team and, while useful, causes massive slowdowns and resource usage and is therefore a net negative.

If this extension is installed, it will cause Typescript Intellisense to be unavailable for approximately 30s after a file save, which definitely slows down the development process.

https://github.com/angular/vscode-ng-language-service/issues/174

**Comment by bjswick33** [comment]
Wanted to confirm that this still occurs. Just spent time going through extensions to resolve intellisense issues and found this extension to be the issue.  They have multiple issues logged on the project.

**Comment by johnpapa** [comment]
Neither of the extensions mentioned are ideal yet

I've had a few chats with the Angular team and I think they have some plans coming on this.

I can't say anything more concrete than that - it's what I've been told, and I trust the team

**Comment by johnpapa** [comment]
this was just updated by the angular team and is now under active dev again
