### ISSUE TITLE
usage 20GB of memory

### ISSUE THREAD

**Issue by kredki** [johnpapa/vscode-angular-essentials#29]
Issue Type: <b>Performance Issue</b>

It happens after saving file.
windows procces explorer shows that vscode use almost 20GB of ram.

Extension version: 0.6.3
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.62GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    43	 15072	code main
    3	    63	  4560	   window (Issue Reporter)
   20	    72	  7336	   shared-process
    0	    11	 10816	   electron-crash-reporter
    3	    62	 11016	   gpu-process
    0	   222	 11808	   window (execute-operation.component.ts - 1000kit-support-tool-ui-ng - Visual Studio Code)
    0	    16	  6820	     watcherService 
    0	    88	  8408	     extensionHost
    0	   198	  5580	       electron_node server.js 
    0	    58	 12292	       electron_node tsserver.js 
   20	  2177	 13460	       electron_node tsserver.js 
    0	    43	 13884	         electron_node typingsInstaller.js typesMap.js 
    0	    30	 14824	       "C:\Users\tliszyns\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\tliszyns\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=8408
    0	     5	  9844	     winpty-process
    0	     4	  8604	       C:\WINDOWS\system32\cmd.exe
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (execute-operation.component.ts - 1000kit-support-tool-ui-ng - Visual Studio Code)
|    Folder (1000kit-support-tool-ui-ng): 387 files
|      File types: scss(78) png(60) ts(55) svg(31) html(13) css(13) json(12)
|                  js(9) eot(9) ttf(9)
|      Conf files: tsconfig.json(2) package.json(1) tslint.json(1);
```

</details>

**Comment by arnotixe** [comment]
In both VSCode 1.41 and vscode-insiders 1.42.0 I get a massive CPU+memory hog when enabling vscode-angular-essentials 0.6.3

Reproduce: just open a .ts document and watch the CPU+RAM go 100% followed by SWAP 100% followed by a memalloc error message in the system tray (I run linux).

Disabling angulare-essentials immediately fixes the problem.

The lower line is 32+32GB RAM/SWAP

![angular_essentials](https://user-images.githubusercontent.com/500938/71498373-20aa7180-282a-11ea-91fe-c47f2b56f5e5.png)

**Comment by kredki** [comment]
For me disabling tslint plugin fixes the problem.
