### ISSUE TITLE
"Go to component" or "!!MISSING: command!! link, is this from this package ?

### ISSUE THREAD

**Issue by borisBelloc** [johnpapa/vscode-angular-essentials#36]
> ---------------------------------------------------------------

### OS and Version?
Windows 10

### Mention any other details that might be useful.

Hello :wave:

When working with Angular project, I don't know why but since 1-2 weeks, I have a `Go to component` link at the top of my HTML file... .

When I click this button, it opens the .ts associated file.
![image](https://user-images.githubusercontent.com/37147299/118857108-f69e9700-b8d7-11eb-9841-b54b2ec0947e.png)

If I'm working with a Electron + Angular project the button is showing an error : `!!MISSING: command!!`
and clicking on it show a toast at the bottom of the screen with `command 'missing' not found`

![image](https://user-images.githubusercontent.com/37147299/118857376-41b8aa00-b8d8-11eb-9878-a16a14674c0d.png)

I have no idea how to debug this nor disable that option or find where it is option from.

Any idea what can I do?
I tried to check `settings.json` and didn't find anything

If I disable `Angular Essentials (Version 11)` I no longer have the grey link; if I enable it back, the grey link comes again.
![image](https://user-images.githubusercontent.com/37147299/118857685-9d833300-b8d8-11eb-8a68-89c452cb642e.png)

> ---------------------------------------------------------------

EDIT : Look like it comes from the addon `Angular Language Service` found in `Angular Essentials (Version 11)` package, maybe I should ask in their hub.
I made an issue : https://github.com/angular/vscode-ng-language-service/issues/1368

**Comment by Alecto** [comment]
The same, I confirm.
If you disable the extension, the error disappears.

**Comment by borisBelloc** [comment]
> The same, I confirm.
> If you disable the extension, the error disappears.

you have got the same error ? when ?
did you try to disable it ?

**Comment by Alecto** [comment]
![image](https://user-images.githubusercontent.com/8464662/118867697-09bb6200-b8ec-11eb-9533-e39c2e3c0b88.png)
![image](https://user-images.githubusercontent.com/8464662/118867776-1dff5f00-b8ec-11eb-987a-1316b9bde5bc.png)

**Comment by Alecto** [comment]
the same error but in a different extension?

**Comment by borisBelloc** [comment]
The extension `Angular Language Service` is inside `Angular Essentials (Version 11)`  package.
That's how I found it.
