### ISSUE TITLE
Broken links in contributing guidelines

### ISSUE THREAD

**Issue by Chealer** [johnpapa/vscode-angular-essentials#38]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS and Version?
> N/A

### Versions
  >N/A

### Repro steps
  >This is not a behavioral bug.

### The log given by the failure.
>This is not a behavioral bug.

### Mention any other details that might be useful.
[CONTRIBUTING.md](https://github.com/johnpapa/vscode-angular-essentials/blob/22fe808f7ff70aa7b4139e497ee35458cf881e2a/CONTRIBUTING.md) contains 5 broken pseudo-links, in its 3 first named subsections, as can be seen in the following screenshot: 
![image](https://user-images.githubusercontent.com/486141/124321409-a1e37280-db4b-11eb-973a-1c4c1ab31f8b.png)

I believe in most cases the target is invalid (I suppose spaces are not supported).

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by johnpapa** [comment]
thanks, fixing
