### ISSUE TITLE
Includes Debugger for Chrome extension

### ISSUE THREAD

**Issue by Chealer** [johnpapa/vscode-angular-essentials#39]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS and Version?
> N/A

### Versions
  >12.0.0

### Repro steps
  >This is not a behavioral bug.

### The log given by the failure.
>This is not a behavioral bug.

### Mention any other details that might be useful.
Angular Essentials includes the Debugger for Chrome extension. While that extension is not explicitly marked as obsolete, [its presentation page](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome&WT.mc_id=javascript-0000-jopapa) includes a warning which seems to say it is deprecated:

> Please file issues on the repo for the new js-debug extension. By default, this extension now delegates to that one which is built-in to VS Code.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by noumanurrahman** [comment]
### I Have Opened a Pull Request In Which I Removed Both Chrome And Edge Debuggers

**Comment by johnpapa** [comment]
fixed in v13

thanks
