### ISSUE TITLE
Package Contents Need updated

### ISSUE THREAD

**Issue by iamstrained** [johnpapa/vscode-angular-essentials#43]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS and Version?
> All OS

### Versions
  > N/A

### Repro steps
  > Attempt to find or review packages in the extension pack.

### The log given by the failure.
> 404, and other notices on depreciated add-ins.

### Mention any other details that might be useful.

Chrome Debugger	and Edge Debugger are listed as deprecated and also a 404, should be removed from this add-in pack recommendation. Also recommend noting that they were removed because they are now largely supported by the bundled js-debug (https://github.com/microsoft/vscode-js-debug). That didn't exist when this add-in pack was created.

**Comment by johnpapa** [comment]
fixed in v13

thanks
