### ISSUE TITLE
Feature Request: Add vscode-angular-html to this extension

### ISSUE THREAD

**Issue by ghaschel** [johnpapa/vscode-angular-essentials#47]
> Please provide us with the following information:
> ---------------------------------------------------------------

I've been using this pack for a long time, and in the meanwhile I've developed a syntax highlighting plugin for angular template files, that eventually got absorbed by [angular-language-service](https://blog.angular.io/version-9-1-of-angular-now-available-typescript-3-8-faster-builds-and-more-eb292f989428), you can check the pull request [here](https://github.com/angular/vscode-ng-language-service/pull/609). But what was merged is still not as highlighted as [my extension](https://github.com/ghaschel/vscode-angular-html#vscode-angular-html) is. So I would like to suggest it to be included.

### OS and Version?
> All of them

### Reasons why this is a good fit for ‘Essentials’:

> 1 - Greater syntax highlighting while still pointing out invalid HTML5 code (for non-angular components only, the invalid syntax highlighting is only applied to the elements it is not allowed by the W3 draft).

> 2 - It also adds highlighting for angular material tags and attributes. Even though it was absorbed by angular-language-service, It is still actively maintained and It does not conflict with angular-language-service itself. It overrides the former's highlighting.

> 3 - I believe a lot of people doesn't know there's such a thing as syntax highlighting for template files, and I'm willing to work with you to make adjustments to make it look really tidy in your Winter is Coming theme

**Comment by johnpapa** [comment]
thanks - closing due to keeping the list short
