### ISSUE TITLE
Essential Logging for Angular

### ISSUE THREAD

**Issue by jocafi** [johnpapa/vscode-angular-essentials#5]
Hi John,

  what library/package do you use for logging in Angular (as **essential** part of an App) ?

 I am looking for a library that:
* I can configure in one place the logger level for production (e.g. WARN or higher) and development (e.g. DEBUG or higher).
* For each angular class I may inform the logger where we are. Then it logs automatically the name of the class using patterns (like log4j in java). 

Example of calling the log in the class ProcessOrder : 
`this.log.error("An error occurred while processing the order.");`

would result in the console:

`07.10.2017 10:34:27 - ProcessOrder: An error occurred while processing the order.`

Thanks!

Best Regards,
Joao Araujo

**Comment by johnpapa** [comment]
better for stackoverflow. please keep the issues here for this extension
