### ISSUE TITLE
In the last update double quote is used

### ISSUE THREAD

**Issue by ingcrengifo** [johnpapa/vscode-angular-essentials#6]
Hi, in the last update when I give "ctrl + shift + f", the character strings are double-quoted and they do not use a quotation mark. I think it's the prettier but I'm not sure, so try to uninstall it but you can not because it's dependency. Is there any way to fix that?

**Comment by wallace41290** [comment]
I agree, the last update really screwed up my formatting in many ways. Turns out you can configure prettier, see - https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode#overview

But what a pain, some kind of config file should have bee provided with recommended settings. Maybe one was or maybe my preferred formatting is not what most people like? But honestly, the double quotes, line breaks at terrible places, all sorts of ugly things in default settings.

@INGCRENGIFO for the double quotes specifically, the quickest way is to add this to your package.json:
```
  "prettier": {
    "singleQuote": "true"
  }
```

**Comment by ingcrengifo** [comment]
Thank you @wallace41290 

That solves the double quotes, but the format is horrible, the spaces and other features.

I hope that @johnpapa will share a configuration file to make the format better. It has changed a lot and at least for me it is not nice, many lines of code go.

**Comment by johnpapa** [comment]
@INGCRENGIFO  You can install an extension, then disable it but leave its child extensions enabled.  by doing this, you can disable the essentials extension and then try each of these others one by one.


Here is my `settings.json` ... I make sure all of my tools use single quotes: prettier, editorconfig, eslint, tslint, etc.

https://gist.github.com/johnpapa/25243977e654cdb3fb77459895e219d9 

I just updated the readme.

**Comment by ingcrengifo** [comment]
Thank you @johnpapa.
"essentials extension" if I want to use it, just "prettier" does not interest me since I change everything, but when I try to disable prettier does not leave me because "angular essentials" depends on it.

**Comment by johnpapa** [comment]
I really find Prettier incredible for team projects, which is why it's in here. I've only changed 2 prettier settings, which is why I keep it. 

See my note above. It explains how you can disable the essentials and then disable any one thing you want.

**Comment by ingcrengifo** [comment]
@johnpapa let me see if I understood, the file that you share should I copy it in ".vscode / settings.json"? Should I do that for all my projects?

![image](https://user-images.githubusercontent.com/12200313/31895231-419b6280-b7d6-11e7-80ad-f828e9b45069.png)

**Comment by johnpapa** [comment]
There are a lot of settings in there. I suggest copying the ones you want, only.

The settings are shared on your computer for all projects.

If you want to share across computers, you can use the `Settings Sync` extension (free) in the marketplace.

**Comment by INGCRENGIFO** [comment]
@johnpapa Thank you so much. If Master John uses all configurations then I will also use them if he improves everything. As you see I have empty the "settings" because I do not know much about it. Thank you very much for sharing.

**Comment by ingcrengifo** [comment]
@johnpapa Thank you so much. If Master @johnpapa uses all configurations then I will also use them if he improves everything. As you see I have empty the "settings" because I do not know much about it. Thank you very much for sharing.
