### ISSUE TITLE
Open Source license?

### ISSUE THREAD

**Issue by sondreb** [johnpapa/vscode-angular-essentials#7]
Is this code not open source?

package.json says "SEE LICENSE IN LICENSE.md", but there is no LICENSE.md file.

This means the code is essentially "All Rights Reserved".

**Comment by ben-d-marks** [comment]
I believe this is a collection of other extensions, and each has its own license...

**Comment by johnpapa** [comment]
yeah. there is no code ... but feel free to add MIT to a PR if you like. I'd accept it.

**Comment by johnpapa** [comment]
i added one
