### ISSUE TITLE
How do I turn off prettier tabsize for html

### ISSUE THREAD

**Issue by lazycuh** [johnpapa/vscode-angular-essentials#9]
I am using Mac OS High Sierra

I have this in my project's `settings.json` file,

```
  "[html]": {
    "editor.tabSize": 4
  },
  "[css]": {
    "editor.tabSize": 4
  },
```

If I turn off angular essentials extension, vscode shows `Spaces: 4` at the bottom right, but if I turn it back on, vscode keeps overriding my settings, reverting to showing `Spaces: 2`

I want 4 spaces for html and (s)css, but this extension keeps forcing me to use 2 spaces.

How do I make my project's local settings take precedent over angular essentials' configurations?

**Comment by gregservera** [comment]
Hello, you can look for an `.editorconfig` file, and edit the `indent_size` setting. This file overrides the `settings.json` file.
